version: "3"
services:

### Flask ##################################################
  docker.web:
    build: flask/
    container_name: flask_web
#    networks:
#        testing_net:
#            ipv4_address: 172.25.1.2
    ports:
      - 56733:80
    volumes:
      - ./flask:/app
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone

### Prometheus #############################################
  prometheus:
    image: prom/prometheus
    container_name: prometheus
#    networks:    
#        testing_net:    
#            ipv4_address: 172.25.1.3
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone

### Grafana ################################################
  grafana:
    build: grafana/
    container_name: grafana
#    networks:
#        testing_net:
#            ipv4_address: 172.25.1.4
    ports:
      - 3000:3000
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone

### Network ################################################

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.25.0.0/16
