FROM grafana/grafana 
COPY ./sample_dashboard.yaml /etc/grafana/provisioning/dashboards/sample.yaml
COPY ./qwerty.json /etc/grafana/provisioning/dashboards/qwerty.json
COPY ./sample_datasourse.yaml /etc/grafana/provisioning/datasources/sample.yaml
